# Generated by Django 4.2.2 on 2023-07-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbname', models.TextField(unique=True)),
                ('hostname', models.TextField(null=True)),
                ('accessid', models.TextField(null=True)),
                ('accesspwd', models.TextField(null=True)),
                ('administrator1', models.TextField()),
                ('administrator2', models.TextField(null=True)),
                ('update_at', models.DateField(auto_now_add=True)),
                ('modified_by', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FormInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formname', models.TextField(unique=True)),
                ('groupname', models.TextField()),
                ('update_at', models.DateField(auto_now_add=True)),
                ('modified_by', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FormList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formname', models.TextField(unique=True)),
                ('form_size', models.IntegerField(default=0)),
                ('groupname', models.TextField()),
                ('form_meta_data', models.TextField()),
                ('update_at', models.DateField(auto_now_add=True)),
                ('modified_by', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.TextField()),
                ('dbname', models.TextField()),
                ('username', models.TextField()),
                ('rolename', models.TextField()),
                ('update_at', models.DateField(auto_now_add=True)),
                ('modified_by', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(unique=True)),
                ('password', models.TextField()),
                ('update_at', models.DateField(auto_now_add=True)),
                ('modified_by', models.TextField()),
            ],
        ),
    ]
